# Generated by Django 2.1.1 on 2018-10-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubmanager', '0002_member_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubmanager.Member')),
            ],
        ),
    ]
